name: Verify pre-release status

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: install pdk
      run: |
        wget https://apt.puppet.com/puppet-tools-release-trusty.deb
        sudo dpkg -i puppet-tools-release-trusty.deb
        sudo apt-get update 
        sudo apt-get install pdk

    - name: run unit tests 
      run: pdk test unit

    - name: run rubocop tests
      run: pdk bundle exec rake rubocop
